const AMOUNT_OF_SHOWN_MOVIES_SCREEN_LG = 12;
const AMOUNT_OF_MOVIES_TO_ADD_SCREEN_LG = 3;
const AMOUNT_OF_SHOWN_MOVIES_SCREEN_MED = 8;
const AMOUNT_MOVIES_TO_ADD_SCREEN_MED = 2;
const AMOUNT_OF_SHOWN_MOVIES_SCREEN_SMALL = 5;
const AMOUNT_OF_MOVIES_TO_ADD_SCREEN_SMALL = 2;
const SHORT_MOVIES_DURATION = 40;
const lARGE_SCREEN_SIZE = 1051;
const MEDIUM_SCREEN_SIZE = 731;

export {
  AMOUNT_OF_SHOWN_MOVIES_SCREEN_LG,
  AMOUNT_OF_MOVIES_TO_ADD_SCREEN_LG,
  AMOUNT_OF_SHOWN_MOVIES_SCREEN_MED,
  AMOUNT_MOVIES_TO_ADD_SCREEN_MED,
  AMOUNT_OF_SHOWN_MOVIES_SCREEN_SMALL,
  AMOUNT_OF_MOVIES_TO_ADD_SCREEN_SMALL,
  SHORT_MOVIES_DURATION,
  lARGE_SCREEN_SIZE,
  MEDIUM_SCREEN_SIZE
};
